project:
  type: website

website:
  title: "Lauren Van Blarcum"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: CV.pdf
        text: CV
      - href: https://laurenvanblarcum.github.io/blog/
        text: Blog
      - Class Assignments.qmd
      - menu: 
        - Assignment 1.qmd
        - Assignment 2.qmd
        - Assignment 3.qmd
        - Assignment 4.qmd
        - Assignment 5.qmd
        - Assignment 6.qmd
        - Assignment 7.qmd
        - Assignment 8.qmd
        - Assignment 9.qmd
        - Assignment 10.qmd
        
      - href: https://laurenvanblarcum.shinyapps.io/laurenvanblarcum/  
        text: Shiny
format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    
editor: visual